//
// Created by gaagaagi on 2026-03-17.
//

#ifndef GRAVITY_BASINS_COLLISIONRESOLVER_H
#define GRAVITY_BASINS_COLLISIONRESOLVER_H


class CollisionResolver {
};


#endif //GRAVITY_BASINS_COLLISIONRESOLVER_H