//
// Created by gaagaagi on 2026-03-17.
//

#ifndef GRAVITY_BASINS_COLLISIONDETECTOR_H
#define GRAVITY_BASINS_COLLISIONDETECTOR_H


class CollisionDetector {
};


#endif //GRAVITY_BASINS_COLLISIONDETECTOR_H